SEED_DATA = [
    # Principles
    {
        "text": "Your data has a nationality. Make sure it stays home.",
        "category": "principle",
        "translation_group": 1,
    },
    {
        "text": "Sovereignty is not about building walls, it's about owning your keys.",
        "category": "principle",
        "translation_group": 2,
    },
    {
        "text": "The cheapest cloud is the one that doesn't cost you your independence.",
        "category": "principle",
        "translation_group": 3,
    },
    {
        "text": "Control your infrastructure, or someone else will control your future.",
        "category": "principle",
        "translation_group": 4,
    },
    {
        "text": "A sovereign cloud is not a luxury — it's a prerequisite for digital autonomy.",
        "category": "principle",
        "translation_group": 5,
    },
    {
        "text": "Reversibility is not optional — if you can't leave, you were never free.",
        "category": "principle",
        "translation_group": 6,
    },
    {
        "text": "Open standards are the foundation of digital independence.",
        "category": "principle",
        "translation_group": 7,
    },
    {
        "text": "Compliance is a snapshot; sovereignty is a posture.",
        "category": "principle",
        "translation_group": 8,
    },
    # Facts
    {
        "text": "The US CLOUD Act allows American authorities to request data stored by US companies, regardless of where the servers are located.",
        "category": "fact",
        "translation_group": 9,
    },
    {
        "text": "GDPR requires that personal data transfers outside the EU have equivalent legal protections — a standard few non-EU countries meet.",
        "category": "fact",
        "translation_group": 10,
    },
    {
        "text": "France's SecNumCloud qualification certifies cloud providers meet the highest security standards defined by ANSSI.",
        "category": "fact",
        "translation_group": 11,
    },
    {
        "text": "The European Data Act, effective September 2025, gives businesses the right to switch cloud providers and port their data freely.",
        "category": "fact",
        "translation_group": 12,
    },
    {
        "text": "Over 80% of the European cloud market is held by three American hyperscalers. Sovereignty starts with choosing alternatives.",
        "category": "fact",
        "translation_group": 13,
    },
    {
        "text": "The Schrems II ruling invalidated the EU-US Privacy Shield, proving that legal frameworks alone cannot guarantee data protection across borders.",
        "category": "fact",
        "translation_group": 14,
    },
    {
        "text": "EUCS (European Cybersecurity Certification Scheme for Cloud Services) aims to create a unified EU-wide certification for cloud providers.",
        "category": "fact",
        "translation_group": 15,
    },
    {
        "text": "Gaia-X is a European initiative to build a federated, transparent data infrastructure that enforces sovereignty by design.",
        "category": "fact",
        "translation_group": 16,
    },
    # Quotes
    {
        "text": "GDPR is not a constraint — it's a competitive advantage.",
        "category": "quote",
        "translation_group": 17,
    },
    {
        "text": "A cloud without jurisdiction is a cloud without guarantees.",
        "category": "quote",
        "translation_group": 18,
    },
    {
        "text": "There is no longer political sovereignty without technological sovereignty.",
        "author": "Bruno Le Maire",
        "source_url": "https://www.vie-publique.fr/discours/283706-bruno-le-maire-07022021-souverainete-numerique-de-lunion-europeenne",
        "category": "quote",
        "translation_group": 19,
    },
    {
        "text": "Data is the raw material of the 21st century. Those who control it, control the economy.",
        "category": "quote",
        "translation_group": 21,
    },
    {
        "text": "The question is not whether you need the cloud, but whose cloud you trust.",
        "category": "quote",
        "translation_group": 22,
    },
    {
        "text": "Europe may have lost the battle to create digital champions capable of taking on US and Chinese companies harvesting personal data, but it can win the war of industrial data.",
        "author": "Thierry Breton",
        "source_url": "https://www.theglobeandmail.com/business/international-business/article-europe-can-win-global-battle-for-industrial-data-says-eu-industry/",
        "category": "quote",
        "translation_group": 34,
    },
    {
        "text": "If we act early on, we can avoid that the AI market gets dominated by a few large players, like we saw happening with digital platforms.",
        "author": "Margrethe Vestager",
        "source_url": "https://www.pymnts.com/artificial-intelligence-2/2024/eu-antitrust-chief-margrethe-vestager-says-ai-needs-vibrant-competition/",
        "category": "quote",
        "translation_group": 35,
    },
    {
        "text": "Digital sovereignty has costs, but the costs of digital dependence are even higher.",
        "author": "Friedrich Merz",
        "source_url": "https://thediplomaticinsight.com/merz-macron-european-digital-sovereignty/",
        "category": "quote",
        "translation_group": 40,
    },
    {
        "text": "The questions of the future will be decided predominantly in the digital realm.",
        "author": "Friedrich Merz",
        "source_url": "https://www.timeslive.co.za/news/world/2025-11-18-europe-must-not-cede-digital-sphere-to-us-and-china-warns-germanys-merz/",
        "category": "quote",
        "translation_group": 41,
    },
    {
        "text": "If we are not well coordinated at EU level, we will still continue to rely on cloud infrastructure outside our continent, even to host governmental data.",
        "author": "Alex Agius Saliba",
        "source_url": "https://forum-europe.com/news/2025/sovereign-cloud-and-ai-where-europe-stands-in-2025-summarising-the-3rd-european-sovereign-cloud-day",
        "category": "quote",
        "translation_group": 42,
    },
    {
        "text": "Today, digital infrastructure is the new public utility.",
        "author": "Alex Agius Saliba",
        "source_url": "https://sigma.world/news/mep-alex-agius-saliba-on-a-digital-wake-up-call/",
        "category": "quote",
        "translation_group": 43,
    },
    {
        "text": "Data sovereignty is about protecting data, through the values of Europe. For OVHcloud, there must be no compromise.",
        "author": "Michel Paulin",
        "source_url": "https://corporate.ovhcloud.com/en/newsroom/news/pfue-conference-digital-sovereignty/",
        "category": "quote",
        "translation_group": 44,
    },
    {
        "text": "Sovereignty is about freedom. You are sovereign when you have the ability to choose transparently and fully aware of the consequences of your choices.",
        "author": "Michel Paulin",
        "source_url": "https://telquel.ma/2024/07/23/michel-paulin-for-companies-like-ovhcloud-morocco-is-the-gateway-to-the-african-continent_1884773",
        "category": "quote",
        "translation_group": 45,
    },
    {
        "text": "The AI race is far from over.",
        "author": "Ursula von der Leyen",
        "source_url": "https://fortune.com/europe/2025/02/11/eu-mobilize-206-billion-dollars-ai-investment-race-far-from-over-chief-von-der-leyen-airbus-mistral-volkswagen/",
        "category": "quote",
        "translation_group": 50,
    },
    {
        "text": "It is so important that we are not dependent on one country or one company when it comes to very critical fields of our economy or society.",
        "author": "Henna Virkkunen",
        "source_url": "https://techxplore.com/news/2026-02-france-ditches-teams-homegrown-european.html",
        "category": "quote",
        "translation_group": 51,
    },
    {
        "text": "The EU must focus on achieving technological sovereignty to ensure its AI systems reflect European principles.",
        "author": "Henna Virkkunen",
        "source_url": "https://www.digitalhubdenmark.dk/post/evp-virkkunen-digital-sovereignty",
        "category": "quote",
        "translation_group": 52,
    },
    # Proverbs
    {
        "text": "He who stores his data under foreign law shall know only uncertainty.",
        "category": "proverb",
        "translation_group": 25,
    },
    {
        "text": "A backup in the same jurisdiction is worth two in the cloud.",
        "category": "proverb",
        "translation_group": 26,
    },
    {
        "text": "Trust is built in millimeters and lost in kilometers — keep your data close.",
        "category": "proverb",
        "translation_group": 27,
    },
    {
        "text": "The wise architect encrypts at rest, in transit, and in regulation.",
        "category": "proverb",
        "translation_group": 28,
    },
    {
        "text": "When the wind of compliance blows, some build walls, others build sovereign clouds.",
        "category": "proverb",
        "translation_group": 29,
    },
    {
        "text": "A lock without a key you own is just a cage.",
        "category": "proverb",
        "translation_group": 30,
    },
    {
        "text": "The best time to own your infrastructure was yesterday. The second best time is now.",
        "category": "proverb",
        "translation_group": 31,
    },
    {
        "text": "Do not store all your eggs in a foreign basket.",
        "category": "proverb",
        "translation_group": 32,
    },
    # --- French translations ---
    # Principes
    {
        "text": "Vos données ont une nationalité. Assurez-vous qu'elles restent chez elles.",
        "category": "principle",
        "language": "fr",
        "translation_group": 1,
    },
    {
        "text": "La souveraineté, ce n'est pas construire des murs, c'est posséder ses clés.",
        "category": "principle",
        "language": "fr",
        "translation_group": 2,
    },
    {
        "text": "Le cloud le moins cher est celui qui ne vous coûte pas votre indépendance.",
        "category": "principle",
        "language": "fr",
        "translation_group": 3,
    },
    {
        "text": "Maîtrisez votre infrastructure, ou quelqu'un d'autre maîtrisera votre avenir.",
        "category": "principle",
        "language": "fr",
        "translation_group": 4,
    },
    {
        "text": "Un cloud souverain n'est pas un luxe — c'est un prérequis pour l'autonomie numérique.",
        "category": "principle",
        "language": "fr",
        "translation_group": 5,
    },
    {
        "text": "La réversibilité n'est pas optionnelle — si vous ne pouvez pas partir, vous n'avez jamais été libre.",
        "category": "principle",
        "language": "fr",
        "translation_group": 6,
    },
    {
        "text": "Les standards ouverts sont le socle de l'indépendance numérique.",
        "category": "principle",
        "language": "fr",
        "translation_group": 7,
    },
    {
        "text": "La conformité est un instantané ; la souveraineté est une posture.",
        "category": "principle",
        "language": "fr",
        "translation_group": 8,
    },
    # Faits
    {
        "text": "Le CLOUD Act américain permet aux autorités américaines de demander l'accès aux données stockées par des entreprises américaines, quel que soit l'emplacement des serveurs.",
        "category": "fact",
        "language": "fr",
        "translation_group": 9,
    },
    {
        "text": "Le RGPD exige que les transferts de données personnelles hors de l'UE bénéficient de protections juridiques équivalentes — un standard que peu de pays non européens respectent.",
        "category": "fact",
        "language": "fr",
        "translation_group": 10,
    },
    {
        "text": "La qualification SecNumCloud de la France certifie que les fournisseurs cloud respectent les plus hautes exigences de sécurité définies par l'ANSSI.",
        "category": "fact",
        "language": "fr",
        "translation_group": 11,
    },
    {
        "text": "Le Data Act européen, en vigueur depuis septembre 2025, donne aux entreprises le droit de changer de fournisseur cloud et de transférer leurs données librement.",
        "category": "fact",
        "language": "fr",
        "translation_group": 12,
    },
    {
        "text": "Plus de 80 % du marché européen du cloud est détenu par trois hyperscalers américains. La souveraineté commence par le choix des alternatives.",
        "category": "fact",
        "language": "fr",
        "translation_group": 13,
    },
    {
        "text": "L'arrêt Schrems II a invalidé le Privacy Shield UE-US, prouvant que les cadres juridiques seuls ne peuvent garantir la protection des données entre continents.",
        "category": "fact",
        "language": "fr",
        "translation_group": 14,
    },
    {
        "text": "L'EUCS (schéma européen de certification de cybersécurité pour les services cloud) vise à créer une certification unifiée à l'échelle de l'UE pour les fournisseurs cloud.",
        "category": "fact",
        "language": "fr",
        "translation_group": 15,
    },
    {
        "text": "Gaia-X est une initiative européenne visant à construire une infrastructure de données fédérée et transparente qui impose la souveraineté par conception.",
        "category": "fact",
        "language": "fr",
        "translation_group": 16,
    },
    # Citations
    {
        "text": "Le RGPD n'est pas une contrainte — c'est un avantage compétitif.",
        "category": "quote",
        "language": "fr",
        "translation_group": 17,
    },
    {
        "text": "Un cloud sans juridiction est un cloud sans garanties.",
        "category": "quote",
        "language": "fr",
        "translation_group": 18,
    },
    {
        "text": "Il n'y a plus de souveraineté politique sans souveraineté technologique.",
        "author": "Bruno Le Maire",
        "source_url": "https://www.vie-publique.fr/discours/283706-bruno-le-maire-07022021-souverainete-numerique-de-lunion-europeenne",
        "category": "quote",
        "language": "fr",
        "translation_group": 19,
    },
    {
        "text": "Les données sont la matière première du XXIe siècle. Ceux qui les contrôlent contrôlent l'économie.",
        "category": "quote",
        "language": "fr",
        "translation_group": 21,
    },
    {
        "text": "La question n'est pas de savoir si vous avez besoin du cloud, mais à quel cloud vous faites confiance.",
        "category": "quote",
        "language": "fr",
        "translation_group": 22,
    },
    {
        "text": "L'Europe a peut-être perdu la bataille pour créer des champions numériques capables de rivaliser avec les entreprises américaines et chinoises qui récoltent les données personnelles, mais elle peut gagner celle des données industrielles.",
        "author": "Thierry Breton",
        "source_url": "https://www.theglobeandmail.com/business/international-business/article-europe-can-win-global-battle-for-industrial-data-says-eu-industry/",
        "category": "quote",
        "language": "fr",
        "translation_group": 34,
    },
    {
        "text": "Si nous agissons tôt, nous pouvons éviter que le marché de l'IA soit dominé par quelques grands acteurs, comme nous l'avons vu avec les plateformes numériques.",
        "author": "Margrethe Vestager",
        "source_url": "https://www.pymnts.com/artificial-intelligence-2/2024/eu-antitrust-chief-margrethe-vestager-says-ai-needs-vibrant-competition/",
        "category": "quote",
        "language": "fr",
        "translation_group": 35,
    },
    {
        "text": "La souveraineté numérique a un coût, mais le coût de la dépendance numérique est encore plus élevé.",
        "author": "Friedrich Merz",
        "source_url": "https://thediplomaticinsight.com/merz-macron-european-digital-sovereignty/",
        "category": "quote",
        "language": "fr",
        "translation_group": 40,
    },
    {
        "text": "Les questions de l'avenir se décideront principalement dans le domaine numérique.",
        "author": "Friedrich Merz",
        "source_url": "https://www.timeslive.co.za/news/world/2025-11-18-europe-must-not-cede-digital-sphere-to-us-and-china-warns-germanys-merz/",
        "category": "quote",
        "language": "fr",
        "translation_group": 41,
    },
    {
        "text": "Si nous ne sommes pas bien coordonnés au niveau européen, nous continuerons à dépendre d'infrastructures cloud situées hors de notre continent, même pour héberger des données gouvernementales.",
        "author": "Alex Agius Saliba",
        "source_url": "https://forum-europe.com/news/2025/sovereign-cloud-and-ai-where-europe-stands-in-2025-summarising-the-3rd-european-sovereign-cloud-day",
        "category": "quote",
        "language": "fr",
        "translation_group": 42,
    },
    {
        "text": "Aujourd'hui, l'infrastructure numérique est le nouveau service public.",
        "author": "Alex Agius Saliba",
        "source_url": "https://sigma.world/news/mep-alex-agius-saliba-on-a-digital-wake-up-call/",
        "category": "quote",
        "language": "fr",
        "translation_group": 43,
    },
    {
        "text": "La souveraineté des données, c'est protéger les données à travers les valeurs de l'Europe. Pour OVHcloud, il ne doit y avoir aucun compromis.",
        "author": "Michel Paulin",
        "source_url": "https://corporate.ovhcloud.com/en/newsroom/news/pfue-conference-digital-sovereignty/",
        "category": "quote",
        "language": "fr",
        "translation_group": 44,
    },
    {
        "text": "La souveraineté, c'est la liberté. Vous êtes souverain quand vous avez la capacité de choisir en toute transparence et en pleine conscience des conséquences de vos choix.",
        "author": "Michel Paulin",
        "source_url": "https://telquel.ma/2024/07/23/michel-paulin-for-companies-like-ovhcloud-morocco-is-the-gateway-to-the-african-continent_1884773",
        "category": "quote",
        "language": "fr",
        "translation_group": 45,
    },
    {
        "text": "La course à l'IA est loin d'être terminée.",
        "author": "Ursula von der Leyen",
        "source_url": "https://fortune.com/europe/2025/02/11/eu-mobilize-206-billion-dollars-ai-investment-race-far-from-over-chief-von-der-leyen-airbus-mistral-volkswagen/",
        "category": "quote",
        "language": "fr",
        "translation_group": 50,
    },
    {
        "text": "Il est essentiel que nous ne dépendions pas d'un seul pays ou d'une seule entreprise pour les domaines critiques de notre économie ou de notre société.",
        "author": "Henna Virkkunen",
        "source_url": "https://techxplore.com/news/2026-02-france-ditches-teams-homegrown-european.html",
        "category": "quote",
        "language": "fr",
        "translation_group": 51,
    },
    {
        "text": "L'UE doit se concentrer sur la souveraineté technologique pour garantir que ses systèmes d'IA reflètent les principes européens.",
        "author": "Henna Virkkunen",
        "source_url": "https://www.digitalhubdenmark.dk/post/evp-virkkunen-digital-sovereignty",
        "category": "quote",
        "language": "fr",
        "translation_group": 52,
    },
    # Proverbes
    {
        "text": "Celui qui stocke ses données sous une loi étrangère ne connaîtra que l'incertitude.",
        "category": "proverb",
        "language": "fr",
        "translation_group": 25,
    },
    {
        "text": "Une sauvegarde dans la même juridiction en vaut deux dans le cloud.",
        "category": "proverb",
        "language": "fr",
        "translation_group": 26,
    },
    {
        "text": "La confiance se construit au millimètre et se perd au kilomètre — gardez vos données près de vous.",
        "category": "proverb",
        "language": "fr",
        "translation_group": 27,
    },
    {
        "text": "L'architecte avisé chiffre au repos, en transit, et en conformité.",
        "category": "proverb",
        "language": "fr",
        "translation_group": 28,
    },
    {
        "text": "Quand souffle le vent de la conformité, certains construisent des murs, d'autres bâtissent des clouds souverains.",
        "category": "proverb",
        "language": "fr",
        "translation_group": 29,
    },
    {
        "text": "Un cadenas dont vous ne possédez pas la clé n'est qu'une cage.",
        "category": "proverb",
        "language": "fr",
        "translation_group": 30,
    },
    {
        "text": "Le meilleur moment pour maîtriser son infrastructure, c'était hier. Le deuxième meilleur moment, c'est maintenant.",
        "category": "proverb",
        "language": "fr",
        "translation_group": 31,
    },
    {
        "text": "Ne mettez pas tous vos œufs dans un panier étranger.",
        "category": "proverb",
        "language": "fr",
        "translation_group": 32,
    },
]
